export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAILURE = "FETCH_ALBUMS_FAILURE";
export const PLAY_SONG = "PLAY_SONG";
export const PLAY_SONG_FAILURE = "PLAY_SONG_FAILURE";
export const PLAY_SONG_SUCCESS = "PLAY_SONG_SUCCESS";
export const RESET_STATE = "RESET_STATE";
